### ISSUE TITLE
Uses the wrong path to open the HTML

### ISSUE THREAD

**Issue by aleksejrs** [nicolas-raoul/OxygenGuide-Android#19]
Can't open the HTML; the browsers/viewers say `file://sdcard/OxygenGuide/index.html` is 404.  Android 5.1.

**Comment by nicolas-raoul** [comment]
Please use the new app instead:
https://play.google.com/store/apps/details?id=org.kiwix.kiwixcustomwikivoyage
Thanks!

**Comment by aleksejrs** [comment]
I downloaded the broken version from https://f-droid.org/repository/browse/?fdid=org.github.OxygenGuide

The new link says "kiwix"; should I just use Kiwix with packages from http://www.kiwix.org/wiki/Content_in_all_languages to avoid having to log into Google?

**Comment by nicolas-raoul** [comment]
Yes, please use this ZIM: http://download.kiwix.org/zim/wikivoyage_en_all.zim

**Comment by aleksejrs** [comment]
OK, thank you.
